//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipek.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5060")]
        public string cfgSipPort {
            get {
                return ((string)(this["cfgSipPort"]));
            }
            set {
                this["cfgSipPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string cfgRingMode {
            get {
                return ((string)(this["cfgRingMode"]));
            }
            set {
                this["cfgRingMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <string>5060</string>
            <string>5060</string>
            <string>5060</string>
            <string>5060</string>
            <string>5060</string>
          </ArrayOfString>
        ")]
        public string cfgSipAccountPorts {
            get {
                return ((string)(this["cfgSipAccountPorts"]));
            }
            set {
                this["cfgSipAccountPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <string>3600</string>
            <string>3600</string>
            <string>3600</string>
            <string>3600</string>
            <string>3600</string>
          </ArrayOfString>
        ")]
        public string cfgSipAccountRegPeriod {
            get {
                return ((string)(this["cfgSipAccountRegPeriod"]));
            }
            set {
                this["cfgSipAccountRegPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string cfgSipAccountDefault {
            get {
                return ((string)(this["cfgSipAccountDefault"]));
            }
            set {
                this["cfgSipAccountDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <string>*</string>
            <string>*</string>
            <string>*</string>
            <string>*</string>
            <string>*</string>
          </ArrayOfString>
        ")]
        public string cfgSipAccountDomains {
            get {
                return ((string)(this["cfgSipAccountDomains"]));
            }
            set {
                this["cfgSipAccountDomains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string cfgCFUFlag {
            get {
                return ((string)(this["cfgCFUFlag"]));
            }
            set {
                this["cfgCFUFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgCFUNumber {
            get {
                return ((string)(this["cfgCFUNumber"]));
            }
            set {
                this["cfgCFUNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgCFNRNumber {
            get {
                return ((string)(this["cfgCFNRNumber"]));
            }
            set {
                this["cfgCFNRNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string cfgCFNRFlag {
            get {
                return ((string)(this["cfgCFNRFlag"]));
            }
            set {
                this["cfgCFNRFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string cfgDNDFlag {
            get {
                return ((string)(this["cfgDNDFlag"]));
            }
            set {
                this["cfgDNDFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string cfgCFBFlag {
            get {
                return ((string)(this["cfgCFBFlag"]));
            }
            set {
                this["cfgCFBFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgCFBNumber {
            get {
                return ((string)(this["cfgCFBNumber"]));
            }
            set {
                this["cfgCFBNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string cfgAAFlag {
            get {
                return ((string)(this["cfgAAFlag"]));
            }
            set {
                this["cfgAAFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string cfgAATimeout {
            get {
                return ((string)(this["cfgAATimeout"]));
            }
            set {
                this["cfgAATimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <string />
            <string />
            <string />
            <string />
            <string />
            <string />
          </ArrayOfString>
        ")]
        public string cfgSipAccountDisplayName {
            get {
                return ((string)(this["cfgSipAccountDisplayName"]));
            }
            set {
                this["cfgSipAccountDisplayName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <string />
            <string />
            <string />
            <string />
            <string />
          </ArrayOfString>
        ")]
        public string cfgSipAccountAddresses {
            get {
                return ((string)(this["cfgSipAccountAddresses"]));
            }
            set {
                this["cfgSipAccountAddresses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <string />
            <string />
            <string />
            <string />
            <string />
          </ArrayOfString>
        ")]
        public string cfgSipAccountPassword {
            get {
                return ((string)(this["cfgSipAccountPassword"]));
            }
            set {
                this["cfgSipAccountPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <string />
            <string />
            <string />
            <string />
            <string />
          </ArrayOfString>
        ")]
        public string cfgSipAccountIds {
            get {
                return ((string)(this["cfgSipAccountIds"]));
            }
            set {
                this["cfgSipAccountIds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <string />
            <string />
            <string />
            <string />
            <string />
          </ArrayOfString>
        ")]
        public string cfgSipAccountUsername {
            get {
                return ((string)(this["cfgSipAccountUsername"]));
            }
            set {
                this["cfgSipAccountUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <string />
            <string />
            <string />
            <string />
            <string />
          </ArrayOfString>
        ")]
        public string cfgSipAccountState {
            get {
                return ((string)(this["cfgSipAccountState"]));
            }
            set {
                this["cfgSipAccountState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <string />
            <string />
            <string />
            <string />
            <string />
            <string />
            <string />
          </ArrayOfString>
        ")]
        public string cfgSipAccountNames {
            get {
                return ((string)(this["cfgSipAccountNames"]));
            }
            set {
                this["cfgSipAccountNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          <ArrayOfString xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" " +
            "xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n            <string>PCMU/8000/1</" +
            "string>\r\n            <string>PCMA/8000/1</string>\r\n          </ArrayOfString>\r\n " +
            "       ")]
        public string cfgCodecList {
            get {
                return ((string)(this["cfgCodecList"]));
            }
            set {
                this["cfgCodecList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <string />
            <string />
            <string />
            <string />
            <string />
            <string />
          </ArrayOfString>
        ")]
        public string cfgSipAccountProxyAddresses {
            get {
                return ((string)(this["cfgSipAccountProxyAddresses"]));
            }
            set {
                this["cfgSipAccountProxyAddresses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgStunServerAddress {
            get {
                return ((string)(this["cfgStunServerAddress"]));
            }
            set {
                this["cfgStunServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string cfgDtmfMode {
            get {
                return ((string)(this["cfgDtmfMode"]));
            }
            set {
                this["cfgDtmfMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <string>0</string>
            <string>0</string>
            <string>0</string>
            <string>0</string>
            <string>0</string>
          </ArrayOfString>
        ")]
        public string cfgSipAccountTransport {
            get {
                return ((string)(this["cfgSipAccountTransport"]));
            }
            set {
                this["cfgSipAccountTransport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string cfgSipPublishEnabled {
            get {
                return ((string)(this["cfgSipPublishEnabled"]));
            }
            set {
                this["cfgSipPublishEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
            <string />
            <string />
            <string />
            <string />
            <string />
          </ArrayOfString>
        ")]
        public string cfgSipAccountIndex {
            get {
                return ((string)(this["cfgSipAccountIndex"]));
            }
            set {
                this["cfgSipAccountIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600")]
        public string cfgRegistrationTimeout {
            get {
                return ((string)(this["cfgRegistrationTimeout"]));
            }
            set {
                this["cfgRegistrationTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string cfgVAD {
            get {
                return ((string)(this["cfgVAD"]));
            }
            set {
                this["cfgVAD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string cfgECTail {
            get {
                return ((string)(this["cfgECTail"]));
            }
            set {
                this["cfgECTail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgNameServer {
            get {
                return ((string)(this["cfgNameServer"]));
            }
            set {
                this["cfgNameServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string cfgUpdgradeSettings {
            get {
                return ((string)(this["cfgUpdgradeSettings"]));
            }
            set {
                this["cfgUpdgradeSettings"] = value;
            }
        }
    }
}
